# Generated by Django 4.0.5 on 2023-02-20 17:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_name', models.CharField(max_length=100)),
                ('ambulance_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed after +91.", regex='^\\+91\\d{12}$')])),
                ('url', models.URLField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemist_name', models.CharField(max_length=100)),
                ('chemist_type', models.CharField(choices=[(1, 'Individual Chemist'), (2, 'Medical Representative'), (3, 'Hospital Chemist'), (4, 'Chemist Chain Branch')], max_length=255)),
                ('url', models.URLField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('display', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_email', models.EmailField(max_length=254, null=True)),
                ('speciality', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('parent_company_name', models.CharField(default=None, max_length=100)),
                ('display', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('display', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('med_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('med_name', models.CharField(default=None, max_length=100, null=True)),
                ('duration', models.IntegerField(default=None, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed after +91.", regex='^\\+91\\d{12}$')])),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='patiend_med',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient'),
        ),
        migrations.CreateModel(
            name='LabPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed after +91.", regex='^\\+91\\d{12}$')])),
                ('number_type', models.CharField(choices=[(1, 'Primary'), (2, 'Assistant'), (3, 'Booking Only'), (4, 'TPA')], default=1, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('lab_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lab')),
            ],
        ),
        migrations.CreateModel(
            name='LabPatient',
            fields=[
                ('lab_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lab')),
                ('patient_lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed after +91.", regex='^\\+91\\d{12}$')])),
                ('number_type', models.CharField(choices=[(1, 'Primary'), (2, 'Assistant'), (3, 'Booking Only'), (4, 'TPA')], default=1, max_length=100)),
                ('hospital_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalPatient',
            fields=[
                ('hos_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospital')),
                ('patient_hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_name', models.CharField(max_length=100)),
                ('fam_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed after +91.", regex='^\\+91\\d{12}$')])),
                ('preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_fam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed after +91.", regex='^\\+91\\d{12}$')])),
                ('number_type', models.CharField(choices=[(1, 'Primary'), (2, 'Assistant'), (3, 'Booking Only'), (4, 'TPA')], default=1, max_length=100)),
                ('doctor_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.doctor')),
                ('patient_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ChemistPhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed after +91.", regex='^\\+91\\d{12}$')])),
                ('number_type', models.CharField(choices=[(1, 'Primary'), (2, 'Assistant'), (3, 'Booking Only'), (4, 'TPA')], default=1, max_length=100)),
                ('chemist_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.chemist')),
            ],
        ),
        migrations.CreateModel(
            name='ChemistPatient',
            fields=[
                ('chemist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemist_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.chemist')),
                ('patient_chemist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AmbulancePhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999999'. 10 digits allowed after +91.", regex='^\\+91\\d{12}$')])),
                ('number_type', models.CharField(choices=[(1, 'Primary'), (2, 'Assistant'), (3, 'Booking Only'), (4, 'TPA')], default=1, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('ambulance_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ambulance')),
            ],
        ),
        migrations.CreateModel(
            name='AmbulancePatient',
            fields=[
                ('ambulance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ambulance')),
                ('patient_ambulance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ailment',
            fields=[
                ('ailment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ailment_type', models.CharField(choices=[('Diabetes', ((1, 'Type - 1'), (2, 'Type - 2'), (3, 'Prediabetes'))), ('Respiratory', ((4, 'Asthma'), (5, 'COPD'), (6, 'Pulmonary Thrombosis'), (7, 'others'))), ('Thyroid', ((8, 'Thyroid'),)), ('Heart Disease', ((9, 'Heart Disease'),)), ('Arthritis', ((10, 'Rheumatoid'), (11, 'Osteoarthritis'), (12, 'Gout'), (13, 'Juvenile arthritis (JA)'), (14, 'Ankylosing spondylitis'), (15, 'SLE'), (16, 'Reactive arthritis.'), (17, 'Psoriatic arthritis -PsA'))), ('Kidney Disease', ((18, 'Kidney Disease'),)), ('Mental Health', ((19, 'Mental Health'),)), ('Lifestyle disorders', ((20, 'Overweight'), (21, 'Cholesterol'), (22, 'Fatty Liver'), (23, 'GERD'), (24, 'BP'), (25, 'Angina'), (26, 'Chest Pain'))), ('TB', ((27, 'TB'),)), ('Cancer', ((28, 'Cancer'),)), ('Respiratory', ((29, 'CNS/ Neurological Problems'),)), ('Liver Disease', ((30, 'Liver Disease'),)), ('Endocrinological Disorders', ((31, 'Endocrinological Disorders'),)), ('Fertility', ((32, 'Fertility'),)), ('PCOS', ((33, 'PCOS'),)), ('Stroke', ((34, 'Stroke'),)), ('IBD', ((35, 'IBD'),)), ('Other, Specify', ((99, 'Other'),))], max_length=100)),
                ('ailment_other_type', models.CharField(default=None, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_ailment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patient')),
            ],
        ),
    ]
