# Generated by Django 4.0.5 on 2022-06-26 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_name', models.CharField(max_length=100)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('Ailment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_type', models.CharField(choices=[('no_coupon', 'adhesive(s)'), ('capsule', 'capsule(s)'), ('cachet', 'cachet(s)'), ('cream', 'cream(s)'), ('dragee', 'dragee(s)')], db_index=True, max_length=100, null=True)),
                ('number_days', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday)'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], db_index=True, max_length=100, null=True)),
                ('schedule_time', models.CharField(choices=[('1', 'Before Breakfast - Simastatin'), ('2', 'After Breakfast - Loratadine'), ('3', 'Before Lunch - Montelukast)'), ('4', 'After Lunch - Simvastatin'), ('5', 'Before Dinner - Loratadine')], db_index=True, max_length=100, null=True)),
                ('level_of_engagement', models.CharField(choices=[('1', 'Daily - Morning and Evening'), ('2', 'Daily - Morning, Lunch, Evening, Dinner'), ('3', 'As per prescription')], db_index=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_prescription', models.FileField(blank=True, null=True, upload_to='prescription/')),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.caregiver')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.doctor')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.medicine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_prescription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
