# Generated by Django 4.0.5 on 2022-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='subscriber',
            field=models.ManyToManyField(blank=True, null=True, to='prescription.subscriber'),
        ),
    ]
