# Generated by Django 4.0.5 on 2022-06-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescription_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='number_days',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], db_index=True, max_length=100, null=True),
        ),
    ]
