# Generated by Django 4.0.5 on 2022-06-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expired',
            field=models.BooleanField(),
        ),
    ]
