# Generated by Django 4.0.5 on 2022-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('duration', models.CharField(choices=[('yearly', 'yearly'), ('monthly', 'monthly')], db_index=True, max_length=100, null=True)),
            ],
        ),
    ]
