# Generated by Django 4.0.5 on 2022-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=150)),
                ('upload', models.FileField(upload_to='paymentlogo')),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('couple', 'Couple'), ('single', 'Single'), ('family_friends', 'Family & Friends')], db_index=True, max_length=255, null=True),
        ),
    ]
